# Generated by Django 2.0.1 on 2018-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('spell_id', models.CharField(max_length=250)),
                ('game_version', models.CharField(max_length=100)),
                ('registered', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('registered',),
            },
        ),
    ]
